### ISSUE TITLE
java.lang.IllegalStateException: Activity has been destroyed

### ISSUE THREAD

**Issue by HolenZhou** [baoyongzhang/android-ActionSheet#12]
java.lang.IllegalStateException: Activity has been destroyed
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1399)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:620)
	at com.talkweb.cloudcampus.view.ActionSheet.show(ActionSheet.java:65)
	at com.talkweb.cloudcampus.view.ActionSheet$Builder.show(ActionSheet.java:484)
	at com.talkweb.cloudcampus.jsbridge.WebActivity.selectImage(WebActivity.java:477)
	at com.talkweb.cloudcampus.jsbridge.WebActivity$CustomChromeClient.openFileChooser(WebActivity.java:343)
	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:859)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4829)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)

已将ActionSheet的show方法中讲commit改为commitAllowingStateLoss，不知为何出现这样的报错？

**Comment by baoyongzhang** [comment]
Activity都销毁了，你为什么还会show，代码逻辑写的有问题吧

**Comment by HolenZhou** [comment]
protected final void selectImage() {
        if (!checkSDcard())
            return;
        String[] selectPicTypeStr = { "拍照","选择相片"};

        mActionSheet = ActionSheet.createBuilder(BaseApplication.getContext(), getSupportFragmentManager())
                .setCancelBtn(true)
                .setCancelButtonTitle("取消")
                .setOtherButtonTitles(selectPicTypeStr)
                .setTextColor(getResources().getColor(R.color.pagerTab_Indicator))
                .setCancelableOnTouchOutside(true)
                .setListener(
                        new ActionSheetListener() {
                            @Override
                            public void onDismiss(ActionSheet actionSheet, boolean isCancel) {
                                if (isCancel) {
                                    UploadUriCallBack(null);
                                }
                            }

                            @Override
                            public void onOtherButtonClick(ActionSheet actionSheet, int index) {
                                switch (index) {
                                    // 相机拍摄
                                    case 0:
                                        openCarcme();
                                        break;
                                    // 手机相册
                                    case 1:
                                        chosePic();
                                        break;
                                    default:
                                        break;
                                }
                            }
                        })
                .show();
    }

这一段代码是在js代码调用安卓摄像头时执行的，友盟上报只见过几次而已，而且我也很难复现，现在只能通过先判断一下当前Activity的状态再show的方式解决了。。。

**Comment by HolenZhou** [comment]
@Override
	public void onDetach() {
		super.onDetach();

		try {
			Field childFragmentManager = Fragment.class.getDeclaredField("mChildFragmentManager");
			childFragmentManager.setAccessible(true);
			childFragmentManager.set(this, null);

		} catch (NoSuchFieldException e) {
			throw new RuntimeException(e);
		} catch (IllegalAccessException e) {
			throw new RuntimeException(e);
		}
	}

我们在ActionSheet加了这个方法

**Comment by baoyongzhang** [comment]
刚才手残把你的comment删掉了，你再发一次哈

**Comment by baoyongzhang** [comment]
我在邮件里看到了。把ChildFragmentManager置空有什么作用？

**Comment by HolenZhou** [comment]
没事儿哈，我刚是说我们通过再ActionSheet中加入下面代码尝试解决：
@Override
	public void onDetach() {
		super.onDetach();

		try {
			Field childFragmentManager = Fragment.class.getDeclaredField("mChildFragmentManager");
			childFragmentManager.setAccessible(true);
			childFragmentManager.set(this, null);

		} catch (NoSuchFieldException e) {
			throw new RuntimeException(e);
		} catch (IllegalAccessException e) {
			throw new RuntimeException(e);
		}
	}

**Comment by HolenZhou** [comment]
是参考这里的：http://stackoverflow.com/questions/15207305/getting-the-error-java-lang-illegalstateexception-activity-has-been-destroyed/15656428#15656428

**Comment by baoyongzhang** [comment]
这不是一回事。

**Comment by baoyongzhang** [comment]
show的时候判断一下manager.isDestroyed()

```java
public void show(FragmentManager manager, String tag) {
        if (!mDismissed || manager.isDestroyed()) {
            return;
        }
        mDismissed = false;
        FragmentTransaction ft = manager.beginTransaction();
        ft.add(this, tag);
        ft.addToBackStack(null);
        ft.commitAllowingStateLoss();
    }
```

**Comment by HolenZhou** [comment]
好的，谢谢
