### ISSUE TITLE
It will not work api level<17 ?

### ISSUE THREAD

**Issue by AnkurJagani** [baoyongzhang/android-ActionSheet#13]
It is giving exception here for api level. i think you  should give this method only in api level>=17.

Please check here: manager.isDestroyed()

You can write like this to avoid the problem:
if(Build.VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN_MR2){
}else{
}

**Comment by HolenZhou** [comment]
Here we use the FragmentManager in "android.support.v4.app", the compiler has no warning, I think it's compatible with the  platforms prior to Android 3.0.
