### ISSUE TITLE
4.x上getNavBarHeight有问题

### ISSUE THREAD

**Issue by zongjingyao** [baoyongzhang/android-ActionSheet#26]
1.1.6中5.x上action sheet会显示在NavBar顶上，4.x上就会有两倍NavBarHeight的高度了

**Comment by zongjingyao** [comment]
刚调试了一下，getNavBarHeight中获取的高度都是144，但是表现不一样。
4.4：
![image](https://cloud.githubusercontent.com/assets/2386640/17966719/98fd8f82-6af5-11e6-80e9-29c5bf237a7f.png)

6.0
<img width="315" alt="6 0" src="https://cloud.githubusercontent.com/assets/2386640/17966761/d987f29a-6af5-11e6-9f11-9bdb59beb729.png">

**Comment by baoyongzhang** [comment]
试试 1.1.7

**Comment by zongjingyao** [comment]
好了~

**Comment by yugai** [comment]
感谢 我也遇到了这个问题。
