### ISSUE TITLE
How to use it to Fragment

### ISSUE THREAD

**Issue by quewen08** [baoyongzhang/android-ActionSheet#31]
I cannot use it to Fragment when I set ActionSheet.
It cannot find getSupportFragmentManager().

**Comment by wangcheng2929** [comment]
change the resource code like this:
FragmentManager fm = getParentFragment() == null ? getFragmentManager() : getChildFragmentManager();
                if (fm != null) {
                    fm.popBackStack();
                    FragmentTransaction ft = fm.beginTransaction();
                    ft.remove(ActionSheet.this);
                    ft.commitAllowingStateLoss();
                }
