### ISSUE TITLE
Action sheet overlapping on bottom navigation bar on lolipop devices.

### ISSUE THREAD

**Issue by UmeshAndroid** [baoyongzhang/android-ActionSheet#7]
While using action sheet and testing on lolipop devices, the action sheet appears above the bottom navigation bar (eg Nexus5) and click event also taking from navigation bar.
How could I use the same action sheet on lolipop devices avoiding overlapping of navigation bar and action sheet?

**Comment by N1cE174** [comment]
Add to method `createView()` in [ActionSheet.java](https://github.com/baoyongzhang/ActionSheetForAndroid/blob/master/code/src/com/baoyz/actionsheet/ActionSheet.java) margin bottom params like this

```java
params.setMargins(0,0,0,getNavBarHeight(getActivity()));
```

where `getNavBarHeight(getActivity())` from [this](http://stackoverflow.com/a/29938139)
