### ISSUE TITLE
android:allowBackup should not be used in library

### ISSUE THREAD

**Issue by lorenzo96** [baoyongzhang/android-ActionSheet#9]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:27:9-36
  	is also present at [com.baoyz.actionsheet:library:1.1.0] AndroidManifest.xml:12:9-35 value=(true)
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:25:5-178:19 to override

**Comment by baoyongzhang** [comment]
Thanks for reminding！
